# Generated by Django 2.2.6 on 2019-10-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_manager', '0002_auto_20191030_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='form_answer',
            field=models.TextField(null=True),
        ),
    ]
