# Generated by Django 2.2.6 on 2019-11-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_manager', '0004_auto_20191031_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
